# Generated by Django 6.0.6 on 2026-06-14 11:26

import api.campeonato.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome de quem vai usar a chave", max_length=100
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=api.campeonato.models.generate_api_key,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expiration_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equipa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("AnoFundacao", models.PositiveIntegerField()),
                (
                    "emblema",
                    models.ImageField(blank=True, null=True, upload_to="emblemas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("posicao", models.CharField(max_length=50)),
                ("nacionalidade", models.CharField(max_length=50)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="jogadores/"),
                ),
                ("lesionado", models.BooleanField(default=False)),
                (
                    "equipa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogadores",
                        to="api.equipa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("golos_casa", models.PositiveIntegerField()),
                ("golos_fora", models.PositiveIntegerField()),
                (
                    "equipa_casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_casa",
                        to="api.equipa",
                    ),
                ),
                (
                    "equipa_fora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_fora",
                        to="api.equipa",
                    ),
                ),
            ],
        ),
    ]
