# Generated by Django 6.0.5 on 2026-05-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("AnoFundacao", models.PositiveIntegerField()),
                (
                    "emblema",
                    models.ImageField(blank=True, null=True, upload_to="emblemas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("posicao", models.CharField(max_length=50)),
                ("nacionalidade", models.CharField(max_length=50)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="jogadores/"),
                ),
                ("lesionado", models.BooleanField(default=False)),
                (
                    "equipa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogadores",
                        to="campeonato.equipa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("golos_casa", models.PositiveIntegerField()),
                ("golos_fora", models.PositiveIntegerField()),
                (
                    "equipa_casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_casa",
                        to="campeonato.equipa",
                    ),
                ),
                (
                    "equipa_fora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos_fora",
                        to="campeonato.equipa",
                    ),
                ),
            ],
        ),
    ]
