# Generated by Django 6.0.4 on 2026-04-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("apresentacao", models.TextField()),
                ("logo", models.ImageField(blank=True, upload_to="licenciaturas/")),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="makingof/")),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(max_length=200)),
                ("orientadores", models.CharField(max_length=200)),
                ("curso", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("link_pdf", models.URLField(blank=True, null=True)),
                ("link_imagem", models.URLField(blank=True, null=True)),
                ("areas", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="projetos/")),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
