# Generated by Django 6.0.4 on 2026-04-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-ano"],
            },
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="imagem",
        ),
        migrations.AddField(
            model_name="makingof",
            name="descricao_processo",
            field=models.TextField(
                default="", help_text="Descrição de decisões e justificação de modelos"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="makingof",
            name="erros_encontrados",
            field=models.TextField(
                blank=True, help_text="Erros encontrados e respetivas correções"
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="imagem_caderno",
            field=models.ImageField(
                blank=True,
                help_text="Registo em papel, DER, etc.",
                null=True,
                upload_to="makingof/",
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="uso_ia",
            field=models.TextField(
                blank=True, help_text="Como a IA contribuiu (ou não) para o processo"
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="conceitos_aplicados",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="video_demo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="link_oficial",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="nivel_interesse",
            field=models.IntegerField(default=1, help_text="Escala de 1 a 5"),
        ),
        migrations.AddField(
            model_name="tfc",
            name="destaque",
            field=models.BooleanField(
                default=False, help_text="Marcar para destacar na página principal"
            ),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docente_link_lusofona",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docente_nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "projetos_associados",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
                (
                    "tecnologias_associadas",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
    ]
