# Generated by Django 6.0.4 on 2026-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_formacao_remove_makingof_descricao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteressePessoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="interesses/"),
                ),
            ],
        ),
    ]
