# Generated by Django 6.0.4 on 2026-04-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_interessepessoal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competencia",
            options={"verbose_name_plural": "Competências"},
        ),
        migrations.AlterModelOptions(
            name="formacao",
            options={"ordering": ["-ano"], "verbose_name_plural": "Formações"},
        ),
        migrations.AlterModelOptions(
            name="interessepessoal",
            options={"verbose_name_plural": "Interesses Pessoais"},
        ),
        migrations.AlterModelOptions(
            name="licenciatura",
            options={"verbose_name_plural": "Licenciaturas"},
        ),
        migrations.AlterModelOptions(
            name="makingof",
            options={"verbose_name_plural": "Making Of"},
        ),
        migrations.AlterModelOptions(
            name="projeto",
            options={"verbose_name_plural": "Projetos"},
        ),
        migrations.AlterModelOptions(
            name="tecnologia",
            options={"verbose_name_plural": "Tecnologias"},
        ),
        migrations.AlterModelOptions(
            name="tfc",
            options={"verbose_name_plural": "TFCs"},
        ),
        migrations.AlterModelOptions(
            name="unidadecurricular",
            options={"verbose_name_plural": "Unidades Curriculares"},
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="curso",
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tfcs",
                to="portfolio.licenciatura",
            ),
        ),
    ]
