# Generated by Django 6.0.4 on 2026-05-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_competencia_options_alter_formacao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricao_processo",
            field=models.TextField(
                help_text="Descrição de decisões e justificação de modelos (Pode usar Markdown)"
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="erros_encontrados",
            field=models.TextField(
                blank=True,
                help_text="Erros encontrados e respetivas correções (Pode usar Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="O que faz, o que permite, o que gostou/não gostou.",
            ),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnologias",
                to="portfolio.tipotecnologia",
            ),
        ),
    ]
