# Generated by Django 6.0.5 on 2026-06-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0006_apikey"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIKey",
        ),
    ]
