# Generated by Django 6.0.4 on 2026-05-15 19:09

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_autores_group(apps, schema_editor):
    """Criar grupo 'autores' com permissões de criar e editar artigos"""
    artigo_content_type = ContentType.objects.get(app_label='artigos', model='artigo')
    
    # Permissões necessárias
    add_artigo = Permission.objects.get(content_type=artigo_content_type, codename='add_artigo')
    change_artigo = Permission.objects.get(content_type=artigo_content_type, codename='change_artigo')
    
    # Criar grupo se não existir
    group, created = Group.objects.get_or_create(name='autores')
    if created:
        group.permissions.add(add_artigo, change_artigo)


def reverse_autores_group(apps, schema_editor):
    """Remover grupo 'autores'"""
    Group.objects.filter(name='autores').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_autores_group, reverse_autores_group),
    ]
